kind: Service
apiVersion: v1
metadata:
  name: tmapp-service
  labels:
    app: tmapp
    role: %targetEnvironment%
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: tmapp
    role: %targetEnvironment%
  ports:
    - port: 5000
      targetPort: 5000